### ISSUE TITLE
Database file not included

### ISSUE THREAD

**Issue by brainyprb** [tuupola/slim-api-skeleton#10]
Please provide the database sql file used as example in the project.

**Comment by tuupola** [comment]
There is no such file. You can create the database entries by calling the API. 

https://github.com/tuupola/slim-api-skeleton#create-a-new-todo

**Comment by tuupola** [comment]
Forgot to mention that if you are not using Vagrant you need to configure the database credentials in the `.env` file and run `bin/db migrate` manually.

**Comment by Fshamri** [comment]
bin' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tuupola** [comment]
Login into the vagrant machine and run the migrate command.

```
$ vagrant ssh
$ cd /vagrant
$ bin/db migrate
```
