### ISSUE TITLE
How to disable cache?

### ISSUE THREAD

**Issue by ganesh35** [tuupola/slim-api-skeleton#11]
In my app I need to be able to enable/disable cache in order to check the results.
How can I disable?

**Comment by tuupola** [comment]
Which cache are you referring to?

**Comment by ganesh35** [comment]
By that question, I am not sure on which cache.   
I am using Angular2 on client side.   
When I create (POST)/ update (PATCH & PUT) a todo record, it is not showing on the list (GET) page.  
I had to clear the cache and re-login and re-list the page to see the new results.

Could not pin-point where the problem is. :(

I tried changing cache setting in file config/middleware.php  but no success
**File**: config/middleware.php
```php
...
$container["Cors"] = function ($container) {
...
        "cache" => 60,
...   
};
```

**Comment by tuupola** [comment]
I would look from Anglular docs why it caches the results.

**Comment by ganesh35** [comment]
Thank you.   I was using golang before slim with the same Angular code.   It worked fine.  I am searching other settings from LAMP stock.

**Comment by ganesh35** [comment]
I have been using my own custom CORS code which is causing the problem.  I revoked to original Cors and everything working fine.

Thank you for your time and support.

**Comment by tuupola** [comment]
Glad you found a solution!
