### ISSUE TITLE
array_intersect(): Argument #2 is not an array

### ISSUE THREAD

**Issue by aguirre1017** [tuupola/slim-api-skeleton#13]
I'm encountering an issue at line 16 of App\Token.php 

`return !!count(array_intersect($scope, $this->decoded->scope));`

saying "array_intersect(): Argument #2 is not an array".

**Comment by tuupola** [comment]
How does your curl request look like? You should send an array which contains the requested scope, for example `--data '["todo.all"]'`.

**Comment by aguirre1017** [comment]
i tried to run this curl:

`curl "http://veravita-member.localhost:88/api/token" --request POST --include --insecure --header "Content-Type: application/json" --data '["todo.all"]' --user test:test`
 
But the system response with:

HTTP/1.1 201 Created
Date: Fri, 16 Jun 2017 09:17:43 GMT
Server: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.21
X-Powered-By: PHP/5.6.21
Content-Length: 418
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE0OTc2MDQ2NjQsImV4cCI6MTQ5NzYxMTg2NCwianRpIjoiOXNlcTJxVFZCUDJvRnFScEppTGdRIiwic3ViIjoidGVzdCIsInNjb3BlIjpudWxsfQ.RQUB0FdW9_fXHea8KhRus9AY1Lhn9tWriSUTgMfyJk4",
    "expires": 1497611864
}<br />
<b>Warning</b>:  array_filter() expects parameter 1 to be array, null given in <b>D:\xampp\htdocs\VeraVitaMember\api\routes\token.php</b> on line <b>34</b><br />

What I might be missing? Thanks!

**Comment by tuupola** [comment]
Just tried with fresh install and do not see that warning.

```
$ curl "http://192.168.50.5/token" --request POST --include --insecure --header "Content-Type: application/json" --data '["todo.all"]' --user test:test
HTTP/1.1 201 Created
Date: Fri, 16 Jun 2017 12:10:35 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.6.30
Content-Length: 291
Connection: close
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE0OTc2MTUwMzUsImV4cCI6MTQ5NzYyMjIzNSwianRpIjoiMndVQWZNaVg0dXpEM2RUNUVpaFhxMyIsInN1YiI6InRlc3QiLCJzY29wZSI6WyJ0b2RvLmFsbCJdfQ.9Un5hsSuQ-WpQlnPftX03EJw-ymxnyPZdRTCH7DQnXw",
    "expires": 1497622235
}
```

However the error suggests that for some reason `$request->getParsedBody()` fails. You could test this by doing `var_dump($requested_scopes)` in `token.php` line 22. It should look something like:

```php
$requested_scopes = $request->getParsedBody();
var_dump($requested_scopes);
````

Now when you do the same curl request you should see something like:

```php
array(1) {
  [0]=>
  string(8) "todo.all"
}
```

**Comment by tuupola** [comment]
No feedback, closing. If problem still exists feel free to reopen.
