### ISSUE TITLE
PostMan

### ISSUE THREAD

**Issue by AbdelMonnem** [tuupola/slim-api-skeleton#14]
Hi
Haw can i test this with PostMan.
I dont anderstand what do you meen by this:
"--data '["todo.all"]' \
    --user test:test"

**Comment by tuupola** [comment]
I do not use PostMan myself but I am sure it has good documentation. `--data '["todo.all"]` is the data which is POST:ed. `--user test:test"` is the HTTP Basic Auth username and password.
