### ISSUE TITLE
Syntax error, malformed JSON

### ISSUE THREAD

**Issue by Fshamri** [tuupola/slim-api-skeleton#17]
I am getting 

> Syntax error, malformed JSON

my request:

 `curl "http://localhost:8888/api/public/todos"     --request POST     --include     --insecure     --header "Authorization: Bearer $TOKEN"    --header "Content-Type: application/json"     --data '{ "title": "Test the API", "order": 10 }'
`
response: 

```
HTTP/1.1 401 Unauthorized
Date: Fri, 23 Jun 2017 20:46:26 GMT
Server: Apache
X-Powered-By: PHP/7.1.1
Content-Length: 93
Content-Type: application/problem+json

{
    "title": "Syntax error, malformed JSON",
    "type": "about:blank",
    "status": 401

```

**Comment by tuupola** [comment]
Your $token might be malformed. How does it look? Does it validate on jwt.io?

```
$ echo $TOKEN
```

**Comment by Fshamri** [comment]
thank you tuupola it works fine
