### ISSUE TITLE
error due to php version

### ISSUE THREAD

**Issue by Fshamri** [tuupola/slim-api-skeleton#19]
I got the following error

> 
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in //vendor/slim/slim/Slim/Container.php on line 149

i googled the error and it could be due to php version. the php version installed in my host is 5.4.

what modification i need to make my api compatible with v. 5.4?

**Comment by tuupola** [comment]
Slim itself needs at least PHP 5.5. Some of the dependencies need at least PHP 5.6. In other words you cannot use this API skeleton with PHP 5.4.
