### ISSUE TITLE
Token not found

### ISSUE THREAD

**Issue by IgorDePaula** [tuupola/slim-api-skeleton#2]
I use the postman with auth basic authorization and user in headers test and password test with post method and in body of request like scope[] = todo.all and scope[] = todo.list, I received the answer statos => ok and the token. But in other request like /dump or /todos i received the answer "token not found".

**Comment by tuupola** [comment]
You need to send to token with the request in either a cookie called `token` or `Authorization: Bearer <token>` header.

**Comment by IgorDePaula** [comment]
Greate, it's work now. But I generate the token, I navigate to http://server/dump, I see the scope "todo.list" (or "todo.all", appear that not suport multiple scope by time) and I try navigate to http://server/todos I received error of scope invalid.

**Comment by tuupola** [comment]
How does your token dump look like? You need to pass an array of wanted scopes. For example the following gives permission to create new todo and read contents of specific todo, but not list or delete or update anything.

```
$ curl "https://192.168.50.52/token"
    --include
    --insecure
    --header "Content-Type: application/json"
    --data '["todo.create", "todo.read"]'
    --user test:test
```

Dump looks something like:

```
[decoded] => stdClass Object
    (
        [iat] => 1456065638
        [exp] => 1456072838
        [jti] => Htn6l9VOlkH4nj5ghfRaKgApM9bwFlQY8FaYcx8ennwd
        [sub] => test
        [scope] => Array
        (
            [0] => todo.create
            [1] => todo.read
        )
    )
```

**Comment by IgorDePaula** [comment]
No, aomething like

[decoded] => stdClass Object
    (
        [iat] => 1456065638
        [exp] => 1456072838
        [jti] => Htn6l9VOlkH4nj5ghfRaKgApM9bwFlQY8FaYcx8ennwd
        [sub] => test
        [scope] => Array
        (
            [scope] => todo.all
        )
    )

If I use the postman and send scope[] = todo.all and scope[] = todo.list my
token decoded has

[decoded] => stdClass Object
    (
        [iat] => 1456065638
        [exp] => 1456072838
        [jti] => Htn6l9VOlkH4nj5ghfRaKgApM9bwFlQY8FaYcx8ennwd
        [sub] => test
        [scope] => Array
        (

        )
    )

If I use the postman and send scope = todo.all  my token decoded has

[decoded] => stdClass Object
    (
        [iat] => 1456065638
        [exp] => 1456072838
        [jti] => Htn6l9VOlkH4nj5ghfRaKgApM9bwFlQY8FaYcx8ennwd
        [sub] => test
        [scope] => Array
        (
            [scope] => todo.all
        )
    )



2016-02-21 11:56 GMT-03:00 Mika Tuupola <notifications@github.com>:

**Comment by tuupola** [comment]
I do not use Postman, but it seems you are not submitting an array of wanted scopes but something else. Quick Google search reveals the [StackOverflow answer](http://stackoverflow.com/questions/12756688/is-it-possible-to-send-an-array-with-the-postman-chrome-extension).

It seems you can just [copy paste the curl example](https://www.getpostman.com/docs/importing_curl) in. Also make sure you are sending proper `Content-Type: application/json` and not form data.

**Comment by IgorDePaula** [comment]
Ok, I will try and post the result here. Thanks by your time.

2016-02-21 12:18 GMT-03:00 Mika Tuupola <notifications@github.com>:

**Comment by IgorDePaula** [comment]
Thanks by your time. I resolved this question like you indicated.

2016-02-21 12:24 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:
