### ISSUE TITLE
Probably a typo error

### ISSUE THREAD

**Issue by llaville** [tuupola/slim-api-skeleton#23]
Mika,

In file `slim-api-skeleton-master\routes\todos.php`, 
```
throw new PreconditionFailedException("Todo has been modified", 412);
```

As precondition failed, I suppose that the reason should be spelled "Todo has not been modified"

Laurent

**Comment by tuupola** [comment]
412 is thrown when somebody else already has modified the todo. This is to prevent overwriting changes if two clients are working on the same todo at the same time.

Other way to say this is that the reason for failing is that todo has already been modified.

**Comment by llaville** [comment]
I prefer (vote +1) for "todo has already been modified". More clear to understand what happened
