### ISSUE TITLE
Token not found

### ISSUE THREAD

**Issue by Fshamri** [tuupola/slim-api-skeleton#24]
I have just cloned your skelton and test it in my laptop and that works fine. i uploaded the skeleton to my cloud with no code modifications but i am getting:

```
{
    "title": "Token not found",
    "type": "about:blank",
    "status": 401
} 
```
when i send post request to create todos. my request is:
`curl "http://mydomain.com/tstapi/public/todos" --request POST --include --insecure  --header "Authorization: Bearer $TOKEN"  --header "Content-Type: application/json"  --data '{ "title": "Test the API", "order": 10 }'`
 
can u please help?

**Comment by tuupola** [comment]
Does `$TOKEN` actually have value? Other than that I would look at the error log and try to figure out what is the difference with the server setup between the dev and live environments.

**Comment by Fshamri** [comment]
`$TOKEN` variable is been set. i took the token generated from /token request. `Token=xxxxx `
i have compared apache modules enabled on both dev. and environment but still having the same problem

**Comment by tuupola** [comment]
Then the problem is Apache and PHP on your live server does not receive the `Authorization: Bearer` header for some reason. I would either check your cloud providers documentation or contact their support.

**Comment by Fshamri** [comment]
my cloud provider is https://www.mochahost.com/support.php. their support is really terrible
