### ISSUE TITLE
vagrant time too long 

### ISSUE THREAD

**Issue by wubin1836** [tuupola/slim-api-skeleton#25]
hi,when I run vagrant The program stopped at "default: Waiting for machine to boot. This may take a few minutes..." .And this step has been going on for hours

![vagrant](https://user-images.githubusercontent.com/22363994/28452806-eda09e32-6e26-11e7-9f04-11bd6eabd0ba.png)

**Comment by tuupola** [comment]
I just tested with fresh install and `$ vagrant up` works ok. I would try stopping the bootup by pressing ctrl-c couple of time and then doing:

```
$ vagrant destroy
$ vagrant up
``

To see if it helps.

**Comment by wubin1836** [comment]
Thanks a lot.It's very helpful.
But If I don't want to use vagrant.How can i run it?
I copied the project to Apache's working path.Is it enough ?

**Comment by tuupola** [comment]
You can install in the same way as you would with any other PHP project. Basically as you said just copy the files to Apache document root. 

See the [configuration section](https://www.slimframework.com/docs/start/web-servers.html) in the Slim documentation and the [Slim forums](http://discourse.slimframework.com/). Additionally refer to documentation of the Linux distribution you are using. [StackOverflow](https://stackoverflow.com/) is also a good place for general computing help.

**Comment by wubin1836** [comment]
Thanks a lot 👍
