### ISSUE TITLE
how to ignore /user but work with /user/create?

### ISSUE THREAD

**Issue by khusanov** [tuupola/slim-api-skeleton#28]

**Comment by tuupola** [comment]
Can you elaborate what you mean with ignoring?

**Comment by khusanov** [comment]
I mean "path" => "/user", "ignore" => "/user/create".
I want to do secure registration

**Comment by tuupola** [comment]
Yes you should be able to do that exactly how you showed. Both `HttpBasicAuthentication` and `JwtAuthentication` take the `path` and `ignore` parameter. Settings below would cause everything  starting with `/user`authenticated with exception of everything starting with `/user/create` which will not be authenticated.

```php
 "path" => "/user",
 "ignore" => "/user/create"
```

For example:

```php
return new HttpBasicAuthentication([
    "path" => "/user",
    "ignore" => "/user/create"
    "users" => [
        "test" => "test"
    ]
]);
```

**Comment by khusanov** [comment]
these users array for client side(for example: android app) or for every client(for example: for every people)?

**Comment by khusanov** [comment]
I want to reg users without token with api_key then I am going to add authenticator

**Comment by ohbiko** [comment]
@khusanov Were you able to find a solution for this?
