### ISSUE TITLE
How to pass "--user test:test" in curl options in php

### ISSUE THREAD

**Issue by Fshamri** [tuupola/slim-api-skeleton#31]
I know this is not a bug, but really seek your help. i am trying to call this api to generate token. so i wrote php function to perform the call. something like:

```
ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
$output = curl_exec($ch);
$info = curl_getinfo($ch);
curl_close($ch); 
```
but i get authentication failed. this i think because the user/pass should be passed in the form of:
--user test:test.
can you please help

**Comment by tuupola** [comment]
Above code looks correct, problem is in somewhere else. I would start debugging it with something like:

1.  Are you calling the correct `$url`?
2. Double check you have correct `$username` and `$password`
3. Can you make the same request with commandline curl?
4. Do you have some other authentication middlewares?
5. What is output of `print_r($info)`?

etc

**Comment by tuupola** [comment]
No feedback, closing.
