### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by swotools** [tuupola/slim-api-skeleton#34]
Hi @tuupola! Does it make sense to add psr6 handler (ie redis or memcache) to the psr7 already implemented? The ETAG don't reduce connection .. or I'm wrong? I lost my way ... I think I need to reduce db conns and  I think I need to add cache handler into api? Otherwise I still use psr6 for single application with misaligned data! How can I continue in the right way?

**Comment by tuupola** [comment]
I think adding a PSR-6 cache for database causes more problems (cache invalidation etc) than it creates solutions. If database is currently a bottleneck I would look into fusing [ProxySQL](http://www.proxysql.com/) as a query cache.
