### ISSUE TITLE
Not using the latest version of psr/http-server-middleware?

### ISSUE THREAD

**Issue by himanshu-tiwari** [tuupola/slim-api-skeleton#36]
I'm getting the following error:

<br />
<b>Fatal error</b>:  Declaration of Tuupola\Middleware\CorsMiddleware::process(Psr\Http\Message\ServerRequestInterface $request, Interop\Http\Server\RequestHandlerInterface $handler): Psr\Http\Message\ResponseInterface must be compatible with Psr\Http\Server\MiddlewareInterface::process(Psr\Http\Message\ServerRequestInterface $request, Psr\Http\Server\RequestHandlerInterface $handler): Psr\Http\Message\ResponseInterface in <b>F:\xampp\htdocs\app\vendor\tuupola\cors-middleware\src\CorsMiddleware.php</b> on line <b>33</b><br /><br />

Is it because starting January 22nd, 2018 [http-interop](https://github.com/http-interop/http-server-middleware) is officially deprecated in favor of PSR-15?

Please respond. Require immediate assistance.

**Comment by himanshu-tiwari** [comment]
I resolved it on my own by installing the latest versions of 

> psr/http-server-handler

and

> psr/http-server-middleware

and thereafter replacing `use Interop\Http\Server\RequestHandlerInterface` with `use Psr\Http\Server\RequestHandlerInterface` and `use Interop\Http\Server\MiddlewareInterface` with `use Psr\Http\Server\MiddlewareInterface` everywhere in the project.

**Comment by tuupola** [comment]
They broke the `http-interop/http-server-middleware`. 

https://github.com/http-interop/http-server-middleware/issues/6 
https://github.com/http-interop/http-server-handler/pull/13.
