### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Slim\Middleware\JwtAuthentication

### ISSUE THREAD

**Issue by csantosrj** [tuupola/slim-api-skeleton#37]
hello everyone, Can someone help me fix this? I cloned this project and executed, my setup xampp, php 7.2 and apache. Thanks.

http://prntscr.com/in3h7c

**Comment by tuupola** [comment]
By installing using the [installing instructions](https://github.com/tuupola/slim-api-skeleton#install) should also install all the needed dependencies.
