### ISSUE TITLE
Validating

### ISSUE THREAD

**Issue by karneaud** [tuupola/slim-api-skeleton#4]
Hi,

Reviewing your package for a possible project. What would you recommend in implementing ORM Model data validation for your package?

**Comment by tuupola** [comment]
Internally Spot uses [Valitron](https://github.com/vlucas/valitron). I just checked Spot website and validation is not really documented. But basically you can pass any Valitron rule when you define a entity. For example  the following validates that email is valid email and between 6 and 255 characters.

```php
class User extends \Spot\Entity
{
    public static function fields()
    {
        return [
            "id" => ["type" => "integer", "primary" => true, "autoincrement" => true],
            "email" => ["type" => "string", "required" => true, "unique" => true,
                "validation" => [
                    "email",
                    "length" => [6, 255]
                ]
            ],
        ];
    }
}
```

**Comment by karneaud** [comment]
aahh...thanks

**Comment by tuupola** [comment]
As a sidenote this is still work in progress project so many things might change. I put this together from several API projects I have been doing lately.

**Comment by karneaud** [comment]
yikes!!! ok
