### ISSUE TITLE
[QUESTION] How to add MySQL ORDER BY

### ISSUE THREAD

**Issue by ohbiko** [tuupola/slim-api-skeleton#41]
I'm looking at the `zend-db` [documentation](https://docs.zendframework.com/zend-db/sql/#order) and they indicate that `ORDER BY` is achieved with something like:
```
$select = new Select;
$select->order('id DESC'); // produces 'id' DESC
```
Your `ZendTodoRepository` `all` function seems to always expect an array.  Was your framework set up with `ORDER BY` in mind?  How can we achieve this?

**Comment by ohbiko** [comment]
Ok awesome that's what I'll be doing.  Was just wondering whether you had that covered.  Thanks!

**Comment by tuupola** [comment]
I just recently converted this to Zend TableGateway and have not needed an `ORDER BY` query yet by myself. But since it is  common use case I  should find a good way to do it. Or at least mention this in docs.

Thanks for the heads up!
