### ISSUE TITLE
Return value of Tuupola\\Middleware\\CorsMiddleware::origin() must be an instance of Tuupola\\Middleware\\void, none returned

### ISSUE THREAD

**Issue by ohbiko** [tuupola/slim-api-skeleton#42]
Hi there,

I'm trying to set up a basic test environment with on my hosting server.  Everything was working fine but I'm suddenly getting a 500 error as indicated in the subject.  Do you know what this is?

Thanks!

EDIT: Also, note that this is the second project I'm installing with the host.  The first one had no issues at all.

**Comment by tuupola** [comment]
What is the PHP version? PHP 7.1 is the minimal requirement for the CORS middleware.

**Comment by ohbiko** [comment]
We’re running PHP 7.2 on Apache 2.4.

**Comment by tuupola** [comment]
Ok that is weird. Unit tests pass [with PHP 7.2](https://travis-ci.org/tuupola/cors-middleware)  and I am also using the middleware myself with PHP 7.2.

Have the files in `vendor/` been edited manually?  The method should look like following:

https://github.com/tuupola/cors-middleware/blob/master/src/CorsMiddleware.php#L159-L165

**Comment by ohbiko** [comment]
I figured the issue out.  My host's cPanel was trying to add some code to the root's `.htaccess` file to dictate the PHP version.  There was some conflict but now all seems fine!  The weird that was that the server was still running PHP7.2 when dumping phpinfo.  BTW I'm running Craft 3 CMS and SLIM on the same environment and everything seems to be working okay!

And no I haven't edited the vendor files manually.  That wouldn't be a very wise thing to do. :)
