### ISSUE TITLE
HttpBasicAuthentication

### ISSUE THREAD

**Issue by StepsTeam** [tuupola/slim-api-skeleton#48]
An additional argument needs to be added to line 211 in /vendor/tuupola/slim-basic-auth/src/HttpBasicAuthentication.php

To reproduce the error, try to use the wrong username and password in the example curl:
$ curl "https://192.168.50.52/token" \
    --request POST \
    --include \
    --insecure \
    --header "Content-Type: application/json" \
    --data '["todo.all"]' \
    --user NOT_TEST:NOT_TEST

The response is:
"Too few arguments to function {closure}(), 2 passed in /opt/lampp/htdocs/payment/vendor/tuupola/slim-basic-auth/src/HttpBasicAuthentication.php on line 211 and exactly 3 expected"

I was able to "fix" this error by changing line 211 to:
$handler_response = $this->options["error"]('ADDITIONAL ARGUMENT', $response, $arguments);

Of course, based on line 144 the response should be:
"title": "Authentication failed", "type": "about:blank", "status": 401

**Comment by StepsTeam** [comment]
A better way to "fix" it is to change /config/middleware.php line 33.

Change from:
"error" => function ($request, $response, $arguments) {

To:
"error" => function ($response, $arguments) {

That way, nothing in /vendor needs to be changed.

**Comment by tuupola** [comment]
Seems I have forgotten to update the code when signature changed. Thanks for the heads up!
