### ISSUE TITLE
Spot2 Relations?

### ISSUE THREAD

**Issue by danielwlockhart** [tuupola/slim-api-skeleton#6]
First, I would like to say how much I am loving this!  I have used this to spin up like 3 APIs now in the blink of an eye.  The latest one I am using requires me to have relationships built into my entities and I was wondering if that was possible with this setup? I did it just like it is in the Spot docs....here is my entity class:

namespace App;
use Spot\EntityInterface;
use Spot\MapperInterface;
use Spot\EventEmitter;
use Tuupola\Base62;
use Ramsey\Uuid\Uuid;
use Psr\Log\LogLevel;

class Chat extends \Spot\Entity
{
    protected static $table = "chats";
    public static function fields()
    {
        return [
            "chat_id" => ["type" => "integer", "unsigned" => true, "primary" => true, "autoincrement" => true],
            "chat_event_id" => ["type" => "integer", "unsigned" => true],
            "chat_expires_at" => ["type" => "string", "length" => 100],
            "chat_created_at" => ["type" => "datetime", "value" => new \DateTime()],
            "chat_updated_at" => ["type" => "datetime", "value" => new \DateTime()]
        ];
    }
    public static function events(EventEmitter $emitter)
    {
        $emitter->on("beforeUpdate", function (EntityInterface $entity, MapperInterface $mapper) {
            $entity->chat_updated_at = new \DateTime();
        });
    }
    public static function relations(MapperInterface $mapper, EntityInterface $entity)
    {
        return [
            'messages' => $mapper->hasMany($entity, 'App\ChatMessage', 'chat_message_chat_id')->order(['chat_message_created_at' => 'ASC']),
        ];
    }
    public function timestamp()
    {
        return $this->chat_updated_at->getTimestamp();
    }
}

and here is my Transformer class for Fractal: 

namespace App;
use App\Chat;
use League\Fractal;
class ChatTransformer extends Fractal\TransformerAbstract
{
    public function transform(Chat $chat)
    {
        return [
            "chat_event_id" => (integer)$chat->chat_event_id ?: 0,
            "chat_expires_at" => (string)$chat->chat_expires_at ?: null,
            "chat_messages" => $chat->messages
        ];
    }
}

Everything else is pretty much setup like you do in your examples.  When I run this, I only get a blank for the 'chat_messages' return even though I know there should be something in there so I was just wondering if I was missing something.

**Comment by tuupola** [comment]
You need to have also have [transformer for your relations](http://fractal.thephpleague.com/transformers/) ie. in this case messages. Something like the following untested code.

```php
class ChatTransformer extends Fractal\TransformerAbstract
{
    protected $availableIncludes = [
        "messages"
    ];

    public function includeMessages(Chat $chat)
    {
        $messages = $chat->messages;
        return $this->collection($messages, new MessageTransformer);
    }

    public function transform(Chat $chat)
    {
        return [
            "chat_event_id" => (integer)$chat->chat_event_id ?: 0,
            "chat_expires_at" => (string)$chat->chat_expires_at ?: null
        ];
    }
}

class ChatMessageTransformer extends Fractal\TransformerAbstract
{
    public function transform(ChatMessage $message)
    {
        return [
            "body" => (string)$message->body ?: null
        ];
    }
}
```

**Comment by danielwlockhart** [comment]
That got it!  Thanks!

**Comment by danielwlockhart** [comment]
Thanks again!  One more question...  What would be different about a
belongsTo relationship?  I tried the same as above and it returned an empty
result...here is my Spot Entity class snippet for relations:

 public static function relations(MapperInterface $mapper, EntityInterface
$entity)

    {

        return [

            'university' => $mapper->belongsTo($entity, 'App\University',
'user_university_id'),

        ];

    }

Here is my transformer snippet
protected $defaultIncludes = [
        "university"
    ];

    public function includeUniversity(User $user)
    {
        $university = $user->university;
        return $this->collection($university, new UniversityTransformer);
    }

I tried swapping it to $this->item because I thought that made more sense
but it throws an error that way saying that it expects an object of type
App/University and got an item of type Spot/Relation/BelongsTo

Sorry to be such a bother...I really appreciate the help!

**Comment by tuupola** [comment]
Not sure if it causes your problem but but `belongsTo` returns one object not collection. 

```php
public function includeUniversity(User $user)
{
    $university = $user->university;
    return $this->item($university, new UniversityTransformer);
}
```

**Comment by MarocStream** [comment]
Hello I have the same issue getting data back using relational the result  i am getting is empty for the statustype  here is my code please advise what am i missing I am new to the Slim Api,
Customer Entity 

namespace App;

use Spot\EntityInterface;
use Spot\MapperInterface;
use Spot\EventEmitter;
use Tuupola\Base62;
use Psr\Log\LogLevel;

class Customers extends \Spot\Entity
{
    protected static $table = "customers";

    public static function fields()
    {
        return [
					"customerid" => ["type" => "integer", "autoincrement" => true, "primary" => true],					"accountid" => ["type" => "string",  "length" => 255, "unique" => true],
					"uid" => ["type" => "string",  "length" => 150, "unique" => true],
					"companyname" => ["type" => "string", "length" => 150],
					"firstname" => ["type" => "string", "length" => 150],
					"middleinitial" => ["type" => "string", "length" => 150],
					"lastname" => ["type" => "string", "length" => 200],
					"emailaddress"   => ["type" => "string", "length" => 255],
					"referralcode"   => ["type" => "string", "length" => 50],
					"customerpassword"   => ["type" => "string", "length" => 50],
					"partnerid"   => ["type" => "integer"],
					"partneragentid"   => ["type" => "string", "length" => 50],
					"ipaddress"   => ["type" => "string", "length" => 15],
			        "datecreated"   => ["type" => "datetime", "value" => new \DateTime()],
		            "dateupdated"   => ["type" => "datetime",  "value" => new \DateTime()],
					"createdby"   => ["type" => "string", "length" => 15],
					"agentid"   => ["type" => "integer"],
					"statusid"   => ["type" => "integer"]
					
        ];
    }


 public static function relations(MapperInterface $mapper, EntityInterface $entity)
{
   return  ["statustype" => $mapper->belongsTo($entity, 'App\StatusTypes', 'statusid') ];

}

Status Type Entity 

namespace App;

use Spot\EntityInterface;
use Spot\MapperInterface;
use Spot\EventEmitter;
use Tuupola\Base62;
use Psr\Log\LogLevel;

class StatusTypes extends \Spot\Entity
{
    protected static $table = "statustypes";

    public static function fields()
    {
        return [
					"statusid" => ["type" => "integer",  "primary" => true],																			
					"statustype" => ["type" => "string", "length" => 10],
				     "datecreated" => ["type" => "datetime","value" => new \DateTime()],
				    "updated_at" => ["type" => "datetime","value" => new \DateTime()]
					
					
        ];
    }
}

Customer Transformer 
namespace App;

use App\Customers;

use League\Fractal;
 
class CustomersTransformer extends Fractal\TransformerAbstract
{
	
	  protected $defaultIncludes  = [
      "statustype"
    ];



    public function transform(Customers $customer)
    {
        return [
           
			"customerid" => (integer)$customer->customerid ?: 0,
			"accountid" => (string)$customer->accountid ?: null,
			"uid" => (string)$customer->uid ?: null,
			"companyname" => (string)$customer->companyname ?: null,
			"firstname" => (string)$customer->firstname ?: null,
			"middleinitial" => (string)$customer->middleinitial ?: null,
			"lastname" => (string)$customer->lastname ?: null,
			"emailaddress" => (string)$customer->emailaddress ?: null,
			"referralcode" => (string)$customer->referralcode ?: null,
			//"customerpassword" => (string)$customer->CustomerPassword ?: null,
			"partnerid" => (integer)$customer->partnerid ?: null,
			"partneragentid" => (string)$customer->partneragentid ?: null,
			"datecreated" => $customer->datecreated ?: null,
			"createdby" => (string)$customer->createdby ?: null,
			"dateupdated" => $customer->dateupdated ?: null,
			"updatedby" => (string)$customer->updatedby ?: null,
			"agentid" => (integer)$customer->agentid ?: null,
			"statusid" => $customer->statusid ?: null,
			//"status" =>  $customer->statustype ?: null,
			//"dateadded" => $package->dateAdded ?: null,
                       "links"        => [
                "self" => "/customers/{$customer->uid}"
            ]
        ];
    }
	


		  public function includeStatusType(Customers $customer)
    {
       		
		 return $this->collection( $customer->statustype, new StatusTypesTransformer() );
    }


}


Status Type Transformer

namespace App;

use App\StatusTypes;
use League\Fractal;

class StatusTypesTransformer extends Fractal\TransformerAbstract
{

    public function transform(StatusTypes $status)
    {
        return
	 [
           
			"statusid" => (int)$status->statusid ?: 0,
			"statustype" => (string)$status->statustype ?: null
			//,
			//"datecreated" => $status->dateadded ?: null,
			//"updated_at" => $status->updated_at ?: null
			
			
			//"dateadded" => $package->dateAdded ?: null,
                //       "links"        => [
             //   "self" => "/status/{$status->id}"
          //  ]
      ];
    }
	
	

}
