### ISSUE TITLE
Dotenv Class not Found 

### ISSUE THREAD

**Issue by Z-Team-Pro** [tuupola/slim-api-skeleton#7]
**Uncaught Error: Class 'Dotenv\Dotenv' not found in /var/www/html/slim-api-skeleton-master/app.php:21
Stack trace:**
This is the Error When i try to call the localhost/todo API just for testing

**Comment by tuupola** [comment]
How did you install the skeleton? If this is just a `git clone` the you must install the dependencies  by running `composer install`.

**Comment by Z-Team-Pro** [comment]
Thanks Its Worked For me
