### ISSUE TITLE
Understanding the Dev environment

### ISSUE THREAD

**Issue by jitendraharpalani22** [tuupola/slim-api-skeleton#8]
I have used Vagrant earlier for building Wordpress sites using VVV or VIP Quickstart. So, I understand the advantages of using vagrant. 

But, in this Slim project I am facing some issues understanding my system: 
* How and where is my database created and hosted respectively? Like if I want to access local DB, how to do I do that. One addition to this setup will be to add phpMyAdmin to view database. 
* I am building a Microservices framework, where I want to clone multiple instances of this project to create various services. Now these services will talk to each other as well. Here comes the second need, it should be very easy to have different urls for different services. Vagrant Hostsupdater comes to my mind. Have you thought of integrating that? 
* It's great that you have already integrated other necessary dependencies required like logging, but if I want to debug using php error logs, where do I access those? 

I will really appreciate if you can shed some light on the above. 

P.S. your thoughts on building microservices architecture using this framework are welcome.

**Comment by tuupola** [comment]
> How and where is my database created and hosted respectively? 

[These two lines](https://github.com/tuupola/slim-api-skeleton/blob/master/Vagrantfile#L61-L62) create the database. Database itself lives inside the Vagrant machine.

> Like if I want to access local DB, how to do I do that. 

Using the mysql command in the Vagrant machine.

```bash
$ mysql -u root example
```

> One addition to this setup will be to add phpMyAdmin to view database.

Yes, you can easily add phpMyAdmin if it fits your needs. It is however outside of the scope of this skeleton.

> I am building a Microservices framework, where I want to clone multiple instances of this project to create various services. Now these services will talk to each other as well. Here comes the second need, it should be very easy to have different urls for different services. Vagrant Hostsupdater comes to my mind. Have you thought of integrating that?

Again outside of the scope of the skeleton. However if you need many instances running at the same time, one way would be to change the  [ip address](https://github.com/tuupola/slim-api-skeleton/blob/master/Vagrantfile#L16) for each Vagrant machine.

> It's great that you have already integrated other necessary dependencies required like logging, but if I want to debug using php error logs, where do I access those?

The operating system / Apache default which is  `/etc/httpd/logs/ssl_error_log`

**Comment by jitendraharpalani22** [comment]
Thanks for the info
